### ISSUE TITLE
Grayscale PCX with 1 plane and 8 bits per pixel doesn't properly convert

### ISSUE THREAD

**Issue by trycatchdonothing** [dbrant/imageformats#1]
Steps to reproduce: 
1) Convert the grayscale marbles PCX image using the below link (gmarbles.pcx)
2) Open the output and see that half of the image is shifted to the wrong position.

http://www.redwoodsoft.com/~dru/museum/gfx/gff/sample/images/pcx/textonly.htm

**Comment by dbrant** [comment]
I can't seem to reproduce... Here's what it looks like when loaded in the demo ImageViewer project:

![image](https://user-images.githubusercontent.com/1682214/31151781-21fba314-a867-11e7-8100-3a4ea9177926.png)

Can you provide a screenshot of what you're seeing?

**Comment by trycatchdonothing** [comment]
This ended up being a corrupt pcx file. I redownloaded the image and it converted as expected. Sorry about that.

**Comment by dbrant** [comment]
No worries!
