### ISSUE TITLE
Issue with 1bpp PCX images.

### ISSUE THREAD

**Issue by quakec** [dbrant/imageformats#2]
The PcxReader recognises these PCX images as 1 bpp (downloaded from the site below) but simply doesn't load them correctly.

After saving them as png or bmp the images are black.

https://people.math.sc.edu/Burkardt/data/pcx/pcx.html

**Comment by dbrant** [comment]
Here is one of the images loaded in the sample app in the project:

![image](https://user-images.githubusercontent.com/1682214/98402956-27069e00-2036-11eb-9e77-484b813c97c4.png)

Looks fine to me. What are you doing to save them as PNG or BMP?

**Comment by quakec** [comment]
The images from this site work: [https://filesamples.com/formats/pcx](https://filesamples.com/formats/pcx) , they are not 1bpp however.


What I have done is simply take the PcxReader class by itself and loaded a file into a Bitmap object like so:

`
static void Main(string[] args)
{
  Bitmap test = PcxReader.Load(@"c:\temp\cat.pcx");
  test.Save(@"c:\temp\cat.bmp", System.Drawing.Imaging.ImageFormat.Bmp);
}
`

**Comment by quakec** [comment]
I have it working on your project, with the only real difference that I can see being the fact you're loading the bitmap in to a windows forms picture box.

The condition in the code which detects 1 bpp and "fixes" the color palette in `PcxReader.Load(Stream stream)` is not being hit:

![image](https://user-images.githubusercontent.com/1788271/98542341-ab505f80-2288-11eb-91a1-a29de6b2afa0.png)

After breaking on the condition and stepping into it manually, the file saves perfectly using Bitmap.Save(...). 

When I run your windows forms project, the palette is never "fixed", this leads me to believe that perhaps the background is left transparent and the picture box is handling the white background itself.

**Comment by dbrant** [comment]
Sorry, I'm still not clear which image(s) are not working for you?
I tried using literally these two lines of code (with the `bunny.pcx` file, which is 1-bit):

```
var bmp = Picture.Load("bunny.pcx");
bmp.Save("bunny.png", ImageFormat.Png);
```

And this works correctly for me.

There cannot be any transparency in the output bitmap, because the bitmap is created as `Format32bppRgb`.

**Comment by quakec** [comment]
This is working for me.  I somehow ended up taking an older revision of PcxReader.cs from here, compared the file to the version in the entire project and lots of diffs!

Apologies for wasting your time.  And thank you for creating this 👍
