### ISSUE TITLE
"white space" character is space, CR, LF, TAB, VT, or FF

### ISSUE THREAD

**Issue by Charltsing** [dbrant/imageformats#5]
PPM、PGM、PBM
"white space" character is space, CR, LF, TAB, VT, or FF (I.e. what the ANSI standard C isspace() function calls white space).

https://netpbm.sourceforge.net/doc/
https://netpbm.sourceforge.net/doc/ppm.html
https://netpbm.sourceforge.net/doc/pgm.html
https://netpbm.sourceforge.net/doc/pbm.html

**Comment by dbrant** [comment]
Thanks for the note.
Can you provide any example PnM files that use these other whitespace characters? I would be much more comfortable updating the decoder if I had sample files to test with.

**Comment by Charltsing** [comment]
ReadLineOfInts，ReadLineOfSingleDigitInts
try use
if ((b >= 9 && b <= 13) || b==32) { break; }   //HT、LF、VT、FF、CR、space 

instead of
if ((b == '\r') || (b == '\n')) { break; }

**Comment by dbrant** [comment]
Can you provide any example PnM files that use these other whitespace characters? I would be much more comfortable updating the decoder if I had sample files to test with.

**Comment by Charltsing** [comment]
https://github.com/atiksoftware/Portable-Viewer/files/11443057/2JohnC1V3.zip

you can  creat header yourself

**Comment by dbrant** [comment]
Those files are perfectly viewable in the current implementation. Do you have any files that the viewer cannot view? Why does it need to be updated?

**Comment by Charltsing** [comment]
I think the code should be written according to image specifications
